### ISSUE TITLE
remove blank(?) descriptions

### ISSUE THREAD

**Issue by susanev** [susanev/gazebo#2]

**Comment by zajoru** [comment]
56, 76, 77, 82, 83, 96, 122, 123, 125, 130, 139, 169, 179, 182, 203, 207, 223, 231, 233, 234, 243, 249, 279, 282, 291, 336, 371, 406, 425, 429, 523, 532, 664, 711, 747, 829, 859, 2377, 2380, 2433, 2453, 2462, 2468, 2502, 2631, 2643, 2644, 2699, 2704

**Comment by susanev** [comment]
56, 76, 77, 82, 83, 96, 122, 123, 125, 130 fixed

**Comment by susanev** [comment]
139, 169, 179, 182, 203, 207, 223, 231, 233, 234 fixed

**Comment by susanev** [comment]
243, 249, 279, 282, 291, 336, 371, 406, 425, 429 fixed

**Comment by susanev** [comment]
523, 532, 664, 711, 747, 829, 859, 2377, 2380, 2433 fixed

**Comment by susanev** [comment]
thank you @zajoru ; all fixed : ]
